import images from './images'

export const fruits = [
    { id: 1, title: 'Uvas', emojis: [images.grapes] },
    { id: 2, title: 'Melón', emojis: [images.melon] },
    { id: 3, title: 'Sandia', emojis: [images.watermelon] },
    { id: 4, title: 'Mandarina', emojis: [images.tangerine] },
    { id: 4, title: 'Limón', emojis: [images.lemon] },
    { id: 5, title: 'Platano', emojis: [images.banana] },
    { id: 6, title: 'Piña', emojis: [images.pineapple] },
    { id: 7, title: 'Mango', emojis: [images.mango] },
    { id: 8, title: 'Manzana', emojis: [images.apple] },
    { id: 9, title: 'Pera', emojis: [images.pear] },
    { id: 10, title: 'Durazno', emojis: [images.peach] },
    { id: 11, title: 'Cereza', emojis: [images.cherries] },
    { id: 12, title: 'Fresa', emojis: [images.strawberry] },
    { id: 13, title: 'Araándano', emojis: [images.blueberries] },
    { id: 14, title: 'Kiwi', emojis: [images.kiwiFruit] },
    { id: 15, title: 'Tomate', emojis: [images.tomato] },
    { id: 16, title: 'Aceituna', emojis: [images.olive] },
    { id: 17, title: 'Coco', emojis: [images.coconut] },
    { id: 18, title: 'Aguacate', emojis: [images.avocado] },
    { id: 19, title: 'Berenjena', emojis: [images.eggplant] },
    { id: 20, title: 'Papa', emojis: [images.potato] },
    { id: 21, title: 'Zanahoria', emojis: [images.carrot] },
    { id: 22, title: 'Mazorca de Maiz', emojis: [images.earOfCorn] },
    { id: 23, title: 'Chile', emojis: [images.hotPepper] },
    { id: 24, title: 'Pimiento', emojis: [images.bellPepper] },
    { id: 25, title: 'Pepino', emojis: [images.cucumber] },
    { id: 26, title: 'Lechuga', emojis: [images.leafyGreen] },
    { id: 27, title: 'Brocoli', emojis: [images.broccoli] },
    { id: 28, title: 'Ajo', emojis: [images.garlic] },
    { id: 29, title: 'Cebolla', emojis: [images.onion] },
    { id: 30, title: 'Champiñon', emojis: [images.mushroom] },
    { id: 31, title: 'Cacahuate', emojis: [images.peanuts] },
    { id: 32, title: 'Frijoles', emojis: [images.beans] },
    { id: 33, title: 'Castaña', emojis: [images.chestnut] },
    { id: 34, title: 'Genjibre', emojis: [images.gingerRoot] },
    { id: 35, title: 'Guisante', emojis: [images.peaPod] },
]

export const movies = [
    { id: 1, title: 'El Rey León', emojis: [images.lion, images.crown] },
    { id: 2, title: 'Titanic', emojis: [images.ship, images.ice] },
    { id: 3, title: 'Rapidos y Furiosos', emojis: [images.racingCar, images.angryFace] },
    { id: 4, title: 'Spiderman', emojis: [images.spider, images.spiderWeb] },
    { id: 5, title: 'Toy Story', emojis: [images.teddyBear, images.cowboyHatFace] },
    { id: 6, title: 'Buscando a Nemo', emojis: [images.magnifyingGlass, images.tropicalFish] },
    { id: 7, title: 'Monsters Inc', emojis: [images.ogre, images.child] },
    { id: 8, title: 'Up', emojis: [images.balloon, images.house] },
    { id: 9, title: 'Forrest Gump', emojis: [images.running, images.chocolateBar, images.scroll] },
    { id: 10, title: 'Harry Potter', emojis: [images.highVoltage, images.books, images.magicWand, images.castle] },
    { id: 11, title: 'Shrek', emojis: [images.ogre, images.castle, images.king] },
]

export const series = [
    { id: 1, title: 'Game of Thrones', emojis: [images.crown, images.dragon, images.snowflake] },
    { id: 2, title: 'The Walking Dead', emojis: [images.zombieMan, images.zombieWoman] },
    { id: 3, title: 'The Big Bang Theory', emojis: [images.scientist, images.laptop, images.singer] },
    { id: 4, title: 'Friends', emojis: [images.family, images.cook] },
    { id: 5, title: 'Breaking Bad', emojis: [images.scientist, images.pill, images.testTube] },
    { id: 6, title: 'Stranger Things', emojis: [images.alien, images.man] },
    { id: 7, title: 'The Simpsons', emojis: [images.family, images.donut, images.beerMug] },
    { id: 8, title: 'The Office', emojis: [images.officeWorker, images.pageFacingUp, images.chartIncreasing] },
    { id: 9, title: 'La Casa de Papel', emojis: [images.moneyBag, images.bank, images.goblin] },
    { id: 10, title: 'The Mandalorian', emojis: [images.alien, images.ringedPlanet, images.baby] },
    { id: 11, title: 'El Juego del Calamar', emojis: [images.redTriangle, images.redSquare, images.redCircle] },
]

export const characters = [
    { id: 1, title: 'Mickey Mouse', emojis: [images.mouseFace, images.gloves] },
    { id: 2, title: 'Mario Bros', emojis: [images.mushroom, images.goblin] },
    { id: 3, title: 'Sonic', emojis: [images.hedgehog, images.runningShoe] },
    { id: 4, title: 'Pikachu', emojis: [images.highVoltage, images.mouseFace] },
    { id: 5, title: 'Bugs Bunny', emojis: [images.rabbitFace, images.carrot] },
    { id: 6, title: 'Bob Esponja', emojis: [images.sponge, images.bubbles] },
    { id: 7, title: 'Homero Simpson', emojis: [images.donut, images.beerMug] },
    { id: 8, title: 'Bart Simpson', emojis: [images.boy, images.skateboard] },
    { id: 9, title: 'Shrek', emojis: [images.ogre, images.castle, images.king] },
    { id: 10, title: 'Doraemon', emojis: [images.catFace, images.hammer] },
    { id: 11, title: 'Papa Pitufo', emojis: [images.oldMan, images.mushroom] },
    { id: 12, title: 'Garfield', emojis: [images.catFace, images.pizza] },
    { id: 13, title: 'Goku', emojis: [images.martialArtsUniform, images.orangeCircle, images.monkey] },
    { id: 14, title: 'Patricio Estrella', emojis: [images.star, images.rock, images.waterWave] },
    { id: 15, title: 'Master Chief', emojis: [images.astronaut, images.waterPistol] },
    { id: 16, title: 'Kratos', emojis: [images.axe, images.classicalBuilding] },
    { id: 17, title: 'Donkey Kong', emojis: [images.gorilla, images.banana] },
    { id: 18, title: 'Ryu', emojis: [images.martialArtsUniform, images.oncomingFist] },
    { id: 19, title: 'Princesa Peach', emojis: [images.king, images.peach] },
    { id: 20, title: 'Pacman', emojis: [images.ghost, images.yellowCircle] },
]

export const videogames = [
    { id: 1, title: 'Super Mario Bros', emojis: [images.mushroom, images.goblin] },
    { id: 2, title: 'Sonic', emojis: [images.hedgehog, images.runningShoe] },
    { id: 3, title: 'Pacman', emojis: [images.ghost, images.yellowCircle] },
    { id: 4, title: 'Tetris', emojis: [images.brick, images.redCircle] },
    { id: 5, title: 'Pokemon', emojis: [images.highVoltage, images.mouseFace] },
    { id: 6, title: 'Donkey Kong', emojis: [images.gorilla, images.banana] },
    { id: 7, title: 'Street Fighter', emojis: [images.martialArtsUniform, images.oncomingFist] },
    { id: 8, title: 'Mortal Kombat', emojis: [images.martialArtsUniform, images.dropOfBlood] },
    { id: 9, title: 'The Legend of Zelda', emojis: [images.dagger, images.shield] },
    { id: 10, title: 'PUBG', emojis: [images.waterPistol, images.cooking] },
    { id: 11, title: 'Fortnite', emojis: [images.waterPistol, images.bowAndArrow] },
    { id: 12, title: 'Call of Duty', emojis: [images.waterPistol, images.bomb] },
    { id: 13, title: 'FIFA', emojis: [images.soccerBall] },
    { id: 14, title: 'MineCraft', emojis: [images.brick, images.crossedSwords] },
    { id: 15, title: 'Among Us', emojis: [images.alien, images.dagger] },
    { id: 16, title: 'Candy Crush', emojis: [images.candy, images.lollipop] },
    { id: 17, title: 'GTA', emojis: [images.automobile, images.waterPistol] },
    { id: 18, title: 'Need for Speed', emojis: [images.automobile, images.policeCar] },
    { id: 19, title: 'Mario Kart', emojis: [images.racingCar, images.mushroom] },
    { id: 20, title: 'Rocket League', emojis: [images.automobile, images.soccerBall] },
]

export const brands = [
    { id: 1, title: 'Apple', emojis: [images.apple, images.mobilePhone] },
    { id: 2, title: 'Samsung', emojis: [images.mobilePhone, images.television] },
    { id: 3, title: 'Amazon', emojis: [images.packageBox, images.shoppingBags] },
    { id: 4, title: 'Google', emojis: [images.magnifyingGlass, images.books] },
    { id: 5, title: 'Facebook', emojis: [images.thumbsUp, images.pageFacingUp] },
    { id: 6, title: 'Microsoft', emojis: [images.laptop, images.window] },
    { id: 7, title: 'Netflix', emojis: [images.movieCamera, images.popcorn] },
    { id: 8, title: 'Spotify', emojis: [images.headphone, images.musicalNote] },
    { id: 9, title: 'Uber', emojis: [images.automobile, images.taxi] },
    { id: 10, title: 'Airbnb', emojis: [images.house, images.personInBed] },
    { id: 11, title: 'TikTok', emojis: [images.musicalNote, images.musicalNotes] },
    { id: 12, title: 'Twitter', emojis: [images.bird, images.pageFacingUp] },
    { id: 13, title: 'Instagram', emojis: [images.camara, images.pageFacingUp] },
    { id: 14, title: 'Snapchat', emojis: [images.ghost, images.camara] },
    { id: 15, title: 'Youtube', emojis: [images.television, images.videoCamera] },
    { id: 16, title: 'Whatsapp', emojis: [images.mobilePhone, images.speechBalloon] },
    { id: 17, title: 'Telegram', emojis: [images.mobilePhone, images.speechBalloon] },
    { id: 18, title: 'Zoom', emojis: [images.videoCamera, images.laptop] },
    { id: 19, title: 'Tinder', emojis: [images.fire, images.speechBalloon] },
    { id: 20, title: 'LinkedIn', emojis: [images.officeWorker, images.pageFacingUp] },
]

export const countries = [
    { id: 1, title: 'México', emojis: [images.mxFlag] },
    { id: 2, title: 'Canada', emojis: [images.caFlag] },
    { id: 3, title: 'Brasil', emojis: [images.brFlag] },
    { id: 4, title: 'Argentina', emojis: [images.arFlag] },
    { id: 5, title: 'Colombia', emojis: [images.coFlag] },
    { id: 6, title: 'Peru', emojis: [images.peFlag] },
    { id: 7, title: 'Chile', emojis: [images.clFlag] },
    { id: 8, title: 'España', emojis: [images.esFlag] },
    { id: 9, title: 'Francia', emojis: [images.frFlag] },
    { id: 10, title: 'Alemania', emojis: [images.deFlag] },
    { id: 11, title: 'Italia', emojis: [images.itFlag] },
    { id: 12, title: 'Japon', emojis: [images.jpFlag] },
    { id: 13, title: 'China', emojis: [images.cnFlag] },
    { id: 14, title: 'Rusia', emojis: [images.ruFlag] },
    { id: 15, title: 'India', emojis: [images.inFlag] },
    { id: 16, title: 'Estados Unidos', emojis: [images.usFlag] },
    { id: 17, title: 'Inglaterra', emojis: [images.gbFlag] },
    { id: 18, title: 'Australia', emojis: [images.auFlag] },
    { id: 19, title: 'Corea del Sur', emojis: [images.krFlag] },
    { id: 20, title: 'Sudafrica', emojis: [images.zaFlag] },
]
