export const movies = [
    { id: 1, title: 'El Rey León', emojis: ['🦁', '👑'] },
    { id: 2, title: 'Titanic', emojis: ['🚢', '🧊'] },
    { id: 3, title: 'Rapidos y Furiosos', emojis: ['🏎️', '😡'] },
    { id: 4, title: 'Spiderman', emojis: ['🕷️', '🕸️'] },
    { id: 5, title: 'Toy Story', emojis: ['🧸', '🤠'] },
    { id: 6, title: 'Buscando a Nemo', emojis: ['🔎', '🐠'] },
    { id: 7, title: 'Monsters Inc', emojis: ['👹', '👧'] },
    { id: 8, title: 'Up', emojis: ['🎈', '🏠'] },
    { id: 9, title: 'Forrest Gump', emojis: ['🏃🏻‍♂️', '🍫', '📜'] },
    { id: 10, title: 'Harry Potter', emojis: ['⚡', '📚', '🪄', '🏰'] },
    { id: 11, title: 'Shrek', emojis: ['👹', '🏰', '👸'] },
]

export const series = [
    { id: 1, title: 'Game of Thrones', emojis: ['👑', '🐉', '❄️'] },
    { id: 2, title: 'The Walking Dead', emojis: ['🧟', '🧟‍♂️', '🧟‍♀️'] },
    { id: 3, title: 'The Big Bang Theory', emojis: ['🧑‍🔬', '🧑‍💻', '🧑‍🎤'] },
    { id: 4, title: 'Friends', emojis: ['👨‍👨‍👧‍👦', '👩‍🍳', '👨‍🦰'] },
    { id: 5, title: 'Breaking Bad', emojis: ['👨‍🔬', '💊', '🧪'] },
    { id: 6, title: 'Stranger Things', emojis: ['👽', '🧑‍🦱', '🧑‍🦰'] },
    { id: 7, title: 'The Simpsons', emojis: ['👨‍👩‍👧‍👦', '🍩', '🍺'] },
    { id: 8, title: 'The Office', emojis: ['👨‍💼', '📄', '📈'] },
    { id: 9, title: 'La Casa de Papel', emojis: ['💰', '🏦', '👺'] },
    { id: 10, title: 'The Mandalorian', emojis: ['👽', '🪐', '👶'] },
]

export const characters = [
    { id: 1, title: 'Mickey Mouse', emojis: ['🐭', '🧢'] },
    { id: 2, title: 'Mario Bros', emojis: ['🍄', '👺'] },
    { id: 3, title: 'Sonic', emojis: ['🦔', '👟'] },
    { id: 4, title: 'Pikachu', emojis: ['⚡', '🐭'] },
    { id: 5, title: 'Bugs Bunny', emojis: ['🐰', '🥕'] },
    { id: 6, title: 'Bob Esponja', emojis: ['🟡', '🧽'] },
    { id: 7, title: 'Homero Simpson', emojis: ['🍩', '🍺'] },
    { id: 8, title: 'Bart Simpson', emojis: ['👦', '🛹'] },
    { id: 9, title: 'Shrek', emojis: ['👹', '🏰', '👸'] },
    { id: 10, title: 'Doraemon', emojis: ['🐱', '🔨'] },
    { id: 11, title: 'Papa Pitufo', emojis: ['👴', '🔵'] },
    { id: 12, title: 'Garfield', emojis: ['🐱', '🍕'] },
]

export const videogames = [
    { id: 1, title: 'Super Mario Bros', emojis: ['🍄', '👺'] },
    { id: 2, title: 'Sonic', emojis: ['🦔', '👟'] },
    { id: 3, title: 'Pacman', emojis: ['👻', '🟡'] },
    { id: 4, title: 'Tetris', emojis: ['🧱', '🔴'] },
    { id: 5, title: 'Pokemon', emojis: ['⚡', '🐭'] },
    { id: 6, title: 'Donkey Kong', emojis: ['🦍', '🍌'] },
    { id: 7, title: 'Street Fighter', emojis: ['🥋', '👊'] },
    { id: 8, title: 'Mortal Kombat', emojis: ['🥋', '🩸'] },
    { id: 9, title: 'The Legend of Zelda', emojis: ['🗡️', '🛡️'] },
    { id: 10, title: 'PUBG', emojis: ['🔫', '🍳'] },
    { id: 11, title: 'Fortnite', emojis: ['🔫', '🏹'] },
    { id: 12, title: 'Call of Duty', emojis: ['🔫', '💣'] },
    { id: 13, title: 'FIFA', emojis: ['⚽', '🎮'] },
    { id: 14, title: 'MineCraft', emojis: ['🧱', '⚔️'] },
    { id: 15, title: 'Among Us', emojis: ['👽', '🔪'] },
    { id: 16, title: 'Candy Crush', emojis: ['🍬', '🍭'] },
    { id: 17, title: 'GTA', emojis: ['🚗', '🔫'] },
    { id: 18, title: 'Need for Speed', emojis: ['🚗', '🚓'] },
    { id: 19, title: 'Mario Kart', emojis: ['🏎️', '🏁'] },
    { id: 20, title: 'Rocket League', emojis: ['🚗', '⚽'] },
]

export const brands = [
    { id: 1, title: 'Apple', emojis: ['🍎', '📱'] },
    { id: 2, title: 'Samsung', emojis: ['📱', '📺'] },
    { id: 3, title: 'Amazon', emojis: ['📦', '🛍️'] },
    { id: 4, title: 'Google', emojis: ['🔍', '📚'] },
    { id: 5, title: 'Facebook', emojis: ['👍', '📄'] },
    { id: 6, title: 'Microsoft', emojis: ['💻', '🪟'] },
    { id: 7, title: 'Netflix', emojis: ['🎥', '🍿'] },
    { id: 8, title: 'Spotify', emojis: ['🎧', '🎵'] },
    { id: 9, title: 'Uber', emojis: ['🚗', '🚕'] },
    { id: 10, title: 'Airbnb', emojis: ['🏠', '🛌'] },
    { id: 11, title: 'TikTok', emojis: ['🎵', '🎶'] },
    { id: 12, title: 'Twitter', emojis: ['🐦', '📄'] },
]

export const countries = [
    { id: 1, title: 'Mexico', emojis: ['🇲🇽'] },
    { id: 2, title: 'Canada', emojis: ['🇨🇦'] },
    { id: 3, title: 'Brasil', emojis: ['🇧🇷'] },
    { id: 4, title: 'Argentina', emojis: ['🇦🇷'] },
    { id: 5, title: 'Colombia', emojis: ['🇨🇴'] },
    { id: 6, title: 'Peru', emojis: ['🇵🇪'] },
    { id: 7, title: 'Chile', emojis: ['🇨🇱'] },
    { id: 8, title: 'España', emojis: ['🇪🇸'] },
    { id: 9, title: 'Francia', emojis: ['🇫🇷'] },
    { id: 10, title: 'Alemania', emojis: ['🇩🇪'] },
    { id: 11, title: 'Italia', emojis: ['🇮🇹'] },
    { id: 12, title: 'Japon', emojis: ['🇯🇵'] },
]
